//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.11 at 11:53:07 AM IST 
//


package com.emoney.mps.api.topup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.emoney.mps.api.topup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.emoney.mps.api.topup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReverseResult }
     * 
     */
    public ReverseResult createReverseResult() {
        return new ReverseResult();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link PaymentResult }
     * 
     */
    public PaymentResult createPaymentResult() {
        return new PaymentResult();
    }

    /**
     * Create an instance of {@link InquiryResult }
     * 
     */
    public InquiryResult createInquiryResult() {
        return new InquiryResult();
    }

    /**
     * Create an instance of {@link BillDetail }
     * 
     */
    public BillDetail createBillDetail() {
        return new BillDetail();
    }

    /**
     * Create an instance of {@link ReversePendingTopUpRequest }
     * 
     */
    public ReversePendingTopUpRequest createReversePendingTopUpRequest() {
        return new ReversePendingTopUpRequest();
    }

    /**
     * Create an instance of {@link InquiryPendingTopUpRequest }
     * 
     */
    public InquiryPendingTopUpRequest createInquiryPendingTopUpRequest() {
        return new InquiryPendingTopUpRequest();
    }

    /**
     * Create an instance of {@link PendingTopUpRequest }
     * 
     */
    public PendingTopUpRequest createPendingTopUpRequest() {
        return new PendingTopUpRequest();
    }

    /**
     * Create an instance of {@link PaidBill }
     * 
     */
    public PaidBill createPaidBill() {
        return new PaidBill();
    }

}
